### ISSUE TITLE
RECORDER/PLAYER //! showArray(a) affiche une case de trop

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#1]
//! showArray(a, cursors=[i]) affiche une case de trop

démo ici:
https://recorder.epixode.fr/player?id=1462893478118

**Comment by epixode** [comment]
C'est voulu et je pense que c'est désirable.  Cette case suivant immédiatement le dernier élément d'un tableau n'a pas de valeur affichée, mais permet d'afficher les curseurs.  C'est utile en fin de boucle, et c'est un cas qui est explicitement autorisé par le standard pour l'arithmétique de pointeurs.

Il faut peut-être afficher cette case spéciale autrement, sans la bordure ou avec un fond différent ?

**Comment by remisharrock** [comment]
Ok pour l'afficher différemment !

**Comment by epixode** [comment]
Fait.
