### ISSUE TITLE
RECORDER: enregistrement des selections dans messages/entrées/sorties/variables possible ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#13]
Tout est dans le titre: 
Si jamais c'est possible, faudra-t-il recommencer les enregistrements déjà existants ?

**Comment by epixode** [comment]
La sélection dans l'entrée était bien enregistrée mais le player ne l'affichait pas, c'est corrigé.
Démo : https://codecast.france-ioi.org/player?id=1464054002144

Pour messages/sorties/variables, il n'est pas possible d'enregistrer la sélection faite par le navigateur (cela ne produit pas d'évènements en javascript), et il serait assez compliqué de remplacer ce mécanisme en analysant les clics souris dans chacun des composants.

**Comment by remisharrock** [comment]
ok, j'ai trouvé une autre méthode en copiant collant et expliquant dans la zone de code ;-)
merci, on peut fermer

**Comment by epixode** [comment]
J'ai vu ça dans ton enregistrement "hello world", c'est super ! ☺
