### ISSUE TITLE
RECORDER: enlever les couleurs en passant du mode EXECUTION au mode EDITION

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#18]
les couleurs de l'execution (vert etc...) ne s'enlèvent pas pendant l'enregistrement quand on passe du mode execution au mode edition.
Avec le player, les couleurs disparaissent bien en changeant de mode.
exemple (qui marche bien du coup car avec le player), a reproduire avec le recorder:
https://codecast.france-ioi.org/player?id=1464026485933

**Comment by epixode** [comment]
C'est corrigé, merci.
