### ISSUE TITLE
RECORDER/PLAYER : scanf / printf float ? 

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#2]
Quelle est la précision du scanf d'un float ? 
exemple:
https://recorder.epixode.fr/player?id=1462894041816

**Comment by epixode** [comment]
Oui, scanf d'un float est supporté et utilise la représentation IEEE 754.  Le programme suivant affiche la représentation hexa du float et démontre qu'il est bien lu (pour l'entrée 3.3, la sortie est f = 0x40533333) :

```
#include <stdio.h>

int main() {
    float f;
    scanf("%f",&f);
    printf("f = 0x%08X\n",*(int*)&f);
    return 0;
}

```

Il semble donc qu'il y ait plutôt un problème d'affichage avec l'implémentation de printf utilisée, qui fait une conversion en double et donne le résultat 3.299999952316284.

**Comment by epixode** [comment]
J'ai écrit un printf plus prôche du C et adapté à l'évaluateur pas à pas :

    https://codecast.france-ioi.org/player?id=1464068730300

**Comment by epixode** [comment]
L'affichage dans la pile est désormais indentique à un printf %f (par défaut 6 chiffres après la virgule) avec en plus la suppression des 0 à droite (que ne fait pas le printf), ce qui donne bien l'affichage "3.3" désiré.
