### ISSUE TITLE
macro #define et execution pas à pas : surlignage décalé

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#22]
démo ici:
https://codecast.france-ioi.org/player?id=1464086898202

**Comment by epixode** [comment]
Un bug produisait des sélections invalides dans l'arbre de syntaxe, c'est corrigé.

En revanche, surligner une zone des caractères contigüs du programme n'est possible que lorsqu'il existe dans le programme une telle zone qui correspond exactement à l'instruction (ou la sous-expression) courante.

Clang a un mécanisme (que j'utilise maintenant) pour sélectionner l'appel d'une macro lorsqu'il correspond exactement à une instruction, mais il ne sélectionne jamais de sous-expression à l'intérieur d'une macro (même lorsque ça pourrait avoir du sens).

En conséquence, pour certaines instructions il n'y a rien dans le programme que l'on puisse surligner.  Je vais ajouter un mécanisme pour continuer l'évaluation jusqu'à ce qu'elle s'arrête sur une expression du programme que l'on puisse sélectionner.
