### ISSUE TITLE
RECORDER/PLAYER: selection qui se décale en mode execution

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#23]
la selection du mode execution (celle qui s'affiche en vert en pas à pas) est décalée au fur et à mesure.
Demo - décalage à partir de     printf("troisième\n");
https://codecast.france-ioi.org/player?id=1464088164146
autre démo:
https://codecast.france-ioi.org/player?id=1464088369749

**Comment by epixode** [comment]
Ce sont les accents qui causent ce décalage.  Clang retourne des positions en octets, et en UTF-8 le é est encodé par 2 octets.  Je n'en tiens pas compte pour le calcul des lignes / colonnes.  Je vais voir si c'est simple à corriger, entre temps tu peux contourner le problème en n'utilisant que des caractères ASCII dans le code source.

**Comment by epixode** [comment]
C'est corrigé et les deux démos se jouent correctement.
