### ISSUE TITLE
player: bloquer l'édition en lecture

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#25]
il est possible d'éditer pendant la lecture (quand le mode edition est activé par le codecast), ce qui pose des problèmes de cohérence.
Il faudrait désactiver la possibilité d'édition de code par l'étudiant alors que la lecture est enclenchée (et le débloquer en pause + mode édition...).

**Comment by epixode** [comment]
En effet c'est un oubli malheureux, merci de l'avoir remarqué !

**Comment by epixode** [comment]
C'est corrigé, l'édition est désormais impossible pendant la lecture.
