### ISSUE TITLE
scanf %f dans un double

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#29]
Est-il possible de faire un scanf %f dans un double ?
J'ai dabord un warning à la compilation et ensuite à l'execution un problème de précision:
https://codecast.france-ioi.org/player?id=1465311747368

**Comment by epixode** [comment]
Il faut utiliser %lf comme en C, cela contente clang et l'évaluateur pas-à-pas :

    https://codecast.france-ioi.org/player?id=1465312316885

L'évaluateur pas-à-pas utilisait par erreur %g au lieu %lf, ce qui est corrigé.

Attention, le %f de l'évaluateur est plus permissif celui du C et correspond au %g qui accepte aussi les exposants (par ex. 1.95e3).
