### ISSUE TITLE
RECORDER: pouvoir rentrer les entrée/sorties avant de démarrer l'enregistrement

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#3]
Peut-on changer l'interface pour pouvoir ajouter les entrées/sorties avant le début de l'enregistrement ?

**Comment by epixode** [comment]
Oui, c'est prévu et presque prêt !

**Comment by epixode** [comment]
Fait, on démarre du plus maintenant directement sur l'écran principal, et l'entrée peut être préparée avant le début de l'enregistrement.
