### ISSUE TITLE
printf %.1f avec 1.95 affiche 2.0 (avec un float mais pas avec un double)

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#30]
en utilisant un float:
https://codecast.france-ioi.org/player?id=1465312486316

**Comment by remisharrock** [comment]
en utilisant printf.1f avec 1.95 et des doubles, il n'y a pas cette erreur:
https://codecast.france-ioi.org/player?id=1465312545427

**Comment by epixode** [comment]
Le comportement de gcc est identique dans les deux cas.

**Comment by remisharrock** [comment]
je ne vais utiliser que des doubles alors ;-) MERCI !

**Comment by epixode** [comment]
Oui, c'est plus facile à comprendre en restant avec des double.

La surprise vient du fait que %f de printf prend un double, donc le compilateur insère automatiquement une conversion implicite de l'argument float, mais l'extension du float 1.95f en double est un tout petit peu supérieure au double 1.95 (en regardant les motifs de bits on comprend facilement pourquoi), ce qui avec un arrondi à 1 chiffre après la virgule affiche 2.0.
