### ISSUE TITLE
Une erreur est survenue !  [object NavigatorUserMediaError]

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#37]
Bonjour, j'ai cette erreur en voulant enregistrer , en rechargeant la page, en haut, j'ai ce message qui s'affiche. Une erreur est survenue ! [object NavigatorUserMediaError]

Dans la console j'ai:
`errors.js:19 NavigatorUserMediaErrorconstraintName: ""message: ""name: "PermissionDeniedError"__proto__: NavigatorUserMediaErrorconstraintName: (...)get constraintName: ()constructor: NavigatorUserMediaError()message: (...)get message: ()name: (...)get name: ()Symbol(Symbol.toStringTag): "NavigatorUserMediaError"__proto__: ObjectwatchError$ @ errors.js:19`

et aussi

`errors.js:19 NavigatorUserMediaError {name: "PermissionDeniedError", message: "", constraintName: ""}watchError$ @ errors.js:19tryCatch @ runtime.js:35invoke @ runtime.js:195prototype.(anonymous function) @ runtime.js:59next @ proc.js:185currCb @ proc.js:240takeCb @ proc.js:277put @ channel.js:56(anonymous function) @ channel.js:119emit @ channel.js:23(anonymous function) @ middleware.js:34dispatch @ applyMiddleware.js:35(anonymous function) @ proc.js:292asap.flush @ asap.js:27asap @ asap.js:15runPutEffect @ proc.js:289runEffect @ proc.js:257next @ proc.js:187currCb @ proc.js:240(anonymous function) @ proc.js:265`

**Comment by epixode** [comment]
La première chose à vérifier est que tu n'aies pas accidentellement refusé l'accès au micro.

Sur Chrome : dans la barre d'adresse, il y a une icone à droite (à côté de l'étoile de mise en favori) qui ressemble au contour d'une caméra stylisée.  En cliquant dessus une popup te permet de vérifier que l'accès au micro est bien autorisé.

**Comment by remisharrock** [comment]
YES MERCI MERCI MERCI :-)
