### ISSUE TITLE
PLAYER : mode plein écran / sortie mode plein écran avec des icônes 

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#4]
serait il possible de placer une icône mode plein écran / sortir mode plein écran pour le player, en utilisant les icones suivantes:
https://thenounproject.com/search/?q=full%20screen&i=15353
https://thenounproject.com/search/?q=full%20screen&i=2816

Serait-il possible de placer ces icônes juste à côté du bouton play / pause ?

**Comment by epixode** [comment]
OK pour ajouter ce bouton à côté du bouton play/pause.

Pour les icones, il me semblerait bon de minimiser l'ajout de dépendances supplémentaires et d'utiliser des icones open-source et gratuites (ce n'est pas le cas de Noun Project il me semble).

Les icones correspondantes de font-awesome sont :

http://fortawesome.github.io/Font-Awesome/icon/expand/
http://fortawesome.github.io/Font-Awesome/icon/compress/

**Comment by remisharrock** [comment]
super pour ces icones avec FA , je valide !

**Comment by epixode** [comment]
Fait et testé.
