### ISSUE TITLE
tableaux de caractères

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#41]
Salut, les tableaux de caractères ne s'affichent pas comme avant, on ne voit pas les caractères
https://codecast.france-ioi.org/player?id=1467233434833

**Comment by epixode** [comment]
Bonjour Rémi,
Effectivement la détection automatique de la taille du tableau semble cassé.  En attentant que je corrige le bug tu peux ajouter l'option n=30 à la directive pour voir toutes les cases s'afficher dans ton exemple.

**Comment by epixode** [comment]
Le problème résultait de l'utilisation du lecteur v2 sur un enregistrement fait avec la v1, le serveur est configuré pour rediriger /player sur /v1/player et ça corrige le problème.
