### ISSUE TITLE
scanf qui modifie une variable qui n'a rien à voir

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#42]
dans cet exemple, je ne comprends pas pourquoi à 10min35s, le scanf modifie la valeur de la variable nbMots:
https://codecast.france-ioi.org/player?id=1467236398342

**Comment by epixode** [comment]
Le problème se produit autour de 08:38, le tableau lettres a pour taille 0 (char lettres[0] = {} sur la pile).

En revanche si je recompile le code source le code s'exécute correctement, donc le problème doit venir d'une incompatibilité entre le code compilé enregistré dans le JSON, et la nouvelle version de l'évaluateur pas à pas.

Si l'enregistrement est précieux, il y a 2 options.  L'une est de le rejouer avec la version précédente de l'évaluateur, l'autre est de mettre à jour les codes compilés dans le JSON.

**Comment by remisharrock** [comment]
ce sont des codecast du MOOC ABC du langage C ; qui serviront de nouveau pour la session 2 (la date n'est pas encore programmée) 
Je ferai une vérification plus globale de tous les codecasts pour lancer la session 2; 
Que veut dire "mettre à jour les codes compilés dans le JSON" ? Est-ce une mise à jour qui peut s'automatiser pour tous les codecasts du prermier MOOC ? si oui, peut-on faire un test avant ? Garde-t-on les mêmes URLs ?
J'ai aussi remarqué que le texte du source est plus gros que lors du lancement en Juin (ancien lecteur codecast), est-ce le cas ?J'ai l'impression sur plusieurs codecasts que le texte dépasse à droite ce qui ne me semblait pas le cas avant.

**Comment by remisharrock** [comment]
j'ai trouvé une autre erreur ici 
https://codecast.france-ioi.org/player?id=1467232086946
ça affiche deux fois tous  au lieu d'afficher Bonjour tous

**Comment by epixode** [comment]
Le problème résultait de l'utilisation du lecteur v2 sur un enregistrement fait avec la v1, le serveur est configuré pour rediriger /player sur /v1/player et ça corrige le problème.
