### ISSUE TITLE
sizeof ;-)

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#43]
Salut, j'ai fait quelques tests avec sizeof , ça renvoie 0 pour les constantes et pour (par exemple) le zeroième élément d'un tableau:
https://codecast.france-ioi.org/player?id=1478255311123

**Comment by epixode** [comment]
Le problème résultait de l'utilisation du lecteur v2 sur un enregistrement fait avec la v1, le serveur est configuré pour rediriger /player sur /v1/player et ça corrige le problème.
