### ISSUE TITLE
valeurs du tableau dépassent dans les variables

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#45]
Tout est dans le titre, voici un exemple (à partir de 12 secondes il faut regarder les variables en haut à gauche):
https://codecast.france-ioi.org/v2/player?id=1478999882335

**Comment by mathias-hiron** [comment]
Bonjour Rémi,

L'affichage des tableaux dans la pile est volontairement limité à deux
lignes, sinon la pile devient illisible dès que tu utilises de grands
tableaux. La vue tableau est là pour avoir une vue plus complète.

Amicalement,
Mathias

**Comment by remisharrock** [comment]
ok je comprends
