### ISSUE TITLE
représentation mémoire

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#46]
bonjour, je ne comprends pas ce qui s'affiche avec  //! showMemory(start=0)
au tout début (secondes 3 à 5)
De plus, je ne comprends pas non plus ce qui s'affiche en appuyant sur la fleche droite une première fois (secondes 6 à 14) ?
https://codecast.france-ioi.org/v2/player?id=1479988949799

a déplacer ici ? https://github.com/France-ioi/fioi-editor2/issues/10

**Comment by epixode** [comment]
C'est corrigé.
