### ISSUE TITLE
petit bug affichage mémoire

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#47]
a écouter ici ;-) 
https://codecast.france-ioi.org/v2/player?id=1480040877926

a déplacer ici ? https://github.com/France-ioi/fioi-editor2/issues/10

**Comment by epixode** [comment]
J'ai corrigé le "saut" au premier scroll (même bug que start=0).

Pour les octets qui dépassent maintenant tout le temps de l'affichage, le plus simple est d'ajouter l'option bytes=22 (environ 32 * 0.66) à la directive :

    //! showMemory(cursors=[&m[ligne][colonne]], start=65535, cursorRows=2, width=.66, bytes=22)
