### ISSUE TITLE
erreur malloc

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#49]
issu d'un message forum :
Bonjour à tous,
j'ai effectué un test basé sur le codecast "Désallouer de la mémoire dans le tas avec free", et j'ai obtenu un résultat pour le moins surprenant:
-> allocation int a
-> allocation double b
-> allocation int c
-> free b
-> allocation int d (qui va occuper la première moitié de la place libérée par b)
-> allocation double e (qui va à l'adresse 0 !!!)
-> déallocation int a
-> allocation int f (qui va à la place libérée par a)
Quelqu'un peut-il expliquer l'allocation étrange de e ?
Voici le code:
int main() {
    //! showMemory(start=272, cursors=[a,b,c,d,e,f])
    int * a = malloc(sizeof(int));
    double * b = malloc(sizeof(double));
    int * c = malloc(sizeof(int));
    free(b);
    int * d = malloc(sizeof(int));
    double * e = malloc(sizeof(double));
    free(a);
    int * f = malloc(sizeof(int));
    return 0;
}
Merci,
JPJ.

**Comment by epixode** [comment]
Bonjour Rémi,
Effectivement il y avait un problème avec l'allocation de d (où le bloc de 12, soit 4 d'entête + 8 pour le double), la valeur de l'entête passe de 0x0D (12|1, indiquant une zone libre de 12 octets) à 0x08 au lieu de 0x0C (où le bit 'libre' est mis à 0, mais la taille ne change pas).  Cela cassait la structure du tas, ce qui était visible par le fait que les 4 octets en 0x114 (entête du bloc alloué pour c) changeait de couler passant de rouge (structure du tas) à noir.
Le cas était prévu dans le code de malloc mais il y avait une petite erreur, corrigée par b7fe6556.

**Comment by remisharrock** [comment]
ok cool, du coup c'est réparé sur la version déployée ?

**Comment by epixode** [comment]
Oui, c'est corrigé sur codecast.france-ioi.org/v2.
