### ISSUE TITLE
PLAYER : en pause, passer directement en mode édition

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#5]
Est-il possible pour le PLAYER de passer en mode édition pour l'apprenant directement après avoir cliqué sur le bouton pause ?

**Comment by epixode** [comment]
Ce serait possible, mais le passage en mode édition supprime l'état de l'évaluateur pas à pas, et l'affichage une fois en pause ne ressemblerait donc pas du tout à l'affichage juste avant la pause.  Cela casserait aussi la possibilité de faire un "seek" en pause.

**Comment by remisharrock** [comment]
ok, on peut fermer cette issue ;-)
