### ISSUE TITLE
Terminal is not diplaying correct value from POT

### ISSUE THREAD

**Issue by bgaultier** [France-ioi/fioi-recorder#60]
When, you're using a POT on virtual Arduino pin 14, you can change the value of the potentiometer but this value won't be printed correctly in the terminal if you use `Serial.println();`

Please have a look at this [example](https://codecast.france-ioi.org/next/player?base=https%3A%2F%2Fcodecast.s3.amazonaws.com%2Fv4%2FIMTA%2F1496339304013)

**Comment by epixode** [comment]
Fixed, thanks.
