### ISSUE TITLE
Player slider is not diplaying correctly

### ISSUE THREAD

**Issue by bgaultier** [France-ioi/fioi-recorder#61]
When you press play, the slider handle is being displayed **under** the blue bar.
CSS property `z-index : 2;` seems to solve this issue 👍 
![capture d ecran 2017-06-01 a 20 07 34](https://cloud.githubusercontent.com/assets/177940/26694010/63bd3258-4706-11e7-893d-9be0d3829d15.png)

**Comment by epixode** [comment]
Fixed, thanks for noticing.
