### ISSUE TITLE
PLAYER: lecture des selections qui ne fonctionne plus

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-recorder#9]
Voici un exemple de lecture avec des selections qui ne fonctionnent plus.
Egalement un problème de son que je dois régler (quand je parle et que je tape au clavier en même temps).
https://codecast.france-ioi.org/player?id=1463739583046

**Comment by epixode** [comment]
J'ai fait des corrections, peux-tu m'indiquer si la lecture est maintenant conforme à ton enregistrement ?

**Comment by remisharrock** [comment]
oui ça à l'air bon, merci !
